# Generated by Django 4.1.5 on 2023-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_token_is_served_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='current_token',
            field=models.IntegerField(),
        ),
    ]
