# Generated by Django 4.1.5 on 2023-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_token_current_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='token',
            name='token_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
